services:
  db:
    image: postgres
    # volumes:
    #   - pg_data:/var/lib/postgresql/data
    #   - pg_backups:/pg_backups
    environment:
      - POSTGRES_USER=booktype
      - POSTGRES_PASSWORD=booktype
      - POSTGRES_DB=booktype
  redis:
    image: redis
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest

  rabbit:
    image: rabbitmq
  bt:
    build: .
    # networks:
    #   - my_network
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - rabbit
      - db
    # links:
    #   - redis
    #   - rabbit
    #   - db