# Generated by Django 5.1 on 2024-08-15 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0016_alter_attachment_id_alter_attributionexclude_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chapter',
            options={'ordering': ('book',), 'verbose_name': 'Chapter', 'verbose_name_plural': 'Chapters'},
        ),
        migrations.AlterModelOptions(
            name='info',
            options={'ordering': ('book',), 'verbose_name': 'Metadata', 'verbose_name_plural': 'Metadata'},
        ),
    ]
